# Apparently this is the "official" way to silence NOTEs generated by R CMD check about symbols
# in pipelines which it misperceives as globals (https://github.com/tidyverse/magrittr/issues/29).
if(getRversion() >= "2.15.1")  utils::globalVariables(c('correct','correct_response','correct_responses','key_press','lag',
  'phase','rt','stim','token'))

#' Process Outcome Reponse Priming Task data file
#'
#' \code{process_orp()} processes data files generated by the Outcome Response Priming task
#' (\url{https://earcanal.github.io/outcome-response-priming/}).
#'
#'@examples
#'\dontrun{
#'orp_df <- expand.grid(token = participants$token) %>%
#'  mutate(path=paste('data/', token, '_finished/outcome-response-priming-task-results.json', sep=''))
#'orp_df <- orp_df %>%
#'group_by(token) %>%
#'  do(., process_orp(.$path, .$token)) %>%
#'  ungroup %>%
#'  left_join(participants, by='token')
#'}
#' @param path Path to data file
#' @param local TRUE for locally saved JSON (default=FALSE)
#' @param p Participant identifier
#' @keywords expfactory outcome response priming
#' @importFrom expfactory process_expfactory_experiment
#' @importFrom magrittr %>%
#' @importFrom dplyr filter select mutate
#' @export
#' @return Data frame
process_orp <- function(path, local=FALSE, p) {
  df <- expfactory::process_expfactory_experiment(path, local) %>%
      mutate(token = p)
 return(df)
}